# fly.toml app configuration file generated for backend-divine-log-6758 on 2024-12-26T16:46:13+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-divine-log-6758'
primary_region = 'atl'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
